channels:
  - anaconda
  - defaults
dependencies:
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - click=7.1.2
  - flask=1.1.2
  - itsdangerous=1.1.0
  - jinja2=2.11.2
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - markupsafe=1.1.1
  - ncurses=6.2
  - openssl=1.1.1h
  - pip=20.2.4
  - python=3.8.5
  - readline=8.0
  - setuptools=50.3.0
  - sqlite=3.33.0
  - tk=8.6.10
  - werkzeug=1.0.1
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
