name: docker-build-and-deploy-app

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Heroku
        run: docker login --username=${{ secrets.HEROKU_USERNAME }} --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com

      - name: Build and push (App Image)
        run: |
          HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku container:push web -a 'sra405-simple-flask-app'
          HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku container:release web -a 'sra405-simple-flask-app'
